const fs = require("fs");
const os = require("os");
const path = require("path");
const { execFileSync } = require("child_process");
const { DatabaseSync } = require("node:sqlite");
const express = require("express");
const request = require("supertest");
const { scrubTestRunnerEnv } = require("../live/live-helpers");
const { createCronService } = require("../../lib/server/cron-service");
const { parseRunLogLine } = require("../../lib/server/cron-run-files");
const { closeCronStoreDb } = require("../../lib/server/cron-store");
const { registerCronRoutes } = require("../../lib/server/routes/cron");

it("projects an outcome actually generated by the pinned OpenClaw cron service through every history API", async () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "cron-pin-"));
  try {
    const resultPath = path.join(root, "result.json");
    execFileSync(process.execPath, ["tests/fixtures/cron-pinned-runtime.mjs", resultPath], {
      env: { ...scrubTestRunnerEnv(), OPENCLAW_STATE_DIR: root, OPENCLAW_CONFIG_PATH: path.join(root, "openclaw.json") },
      timeout: 20000, encoding: "utf8", stdio: "pipe",
    });
    const actual = JSON.parse(fs.readFileSync(resultPath, "utf8"));
    expect(actual.version).toBe(require("../../package.json").dependencies.openclaw);
    expect(actual.result).toEqual({ ok: true, ran: true });
    expect(actual.queued).toBe(1);
    expect(actual.history.total).toBe(1);
    expect(actual.events.some((event) => event.action === "finished")).toBe(true);
    const dbPath = path.join(root, "state", "openclaw.sqlite");
    const db = new DatabaseSync(dbPath, { readOnly: true });
    const schemaBefore = db.prepare("SELECT type, name, sql FROM sqlite_master ORDER BY name").all();
    expect(db.prepare("SELECT COUNT(*) AS n FROM task_runs WHERE runtime = 'cron'").get().n).toBe(1);
    expect(db.prepare("SELECT name FROM sqlite_master WHERE name = 'cron_run_logs'").get()).toBeUndefined();
    const service = createCronService({ OPENCLAW_DIR: root, getInstalledVersion: () => actual.version,
      clawCmd: () => { throw new Error("A history read must not spawn the CLI"); }, getSessionUsageByKeyPattern: () => ({}) });
    const app = express();
    registerCronRoutes({ app, requireAuth: (_req, _res, next) => next(), cronService: service });
    const response = await request(app).get(`/api/cron/jobs/${actual.jobId}/runs`);
    expect(response.status).toBe(200);
    const expected = JSON.parse(JSON.stringify(parseRunLogLine(JSON.stringify(actual.history.entries[0]), actual.jobId)));
    expect(response.body.runs.entries).toEqual([expected]);
    const usage = await request(app).get(`/api/cron/jobs/${actual.jobId}/usage`);
    expect(usage.body.usage.totals).toMatchObject({ durationSamples: 1, totalDurationMs: expected.durationMs });
    const trends = await request(app).get(`/api/cron/jobs/${actual.jobId}/trends`).set("x-client-timezone", "America/New_York");
    expect(trends.body.trends.points.reduce((sum, point) => sum + point.ok, 0)).toBe(1);
    const bulk = await request(app).get("/api/cron/runs/bulk");
    expect(bulk.body.runs.byJobId[actual.jobId].entries).toEqual([expected]);
    expect(db.prepare("SELECT type, name, sql FROM sqlite_master ORDER BY name").all()).toEqual(schemaBefore);
    db.close();
  } finally {
    closeCronStoreDb();
    fs.rmSync(root, { recursive: true, force: true });
  }
});
