module.exports = {
  domain: "cron",
  title: "Cron Jobs",
  ops: [
    {
      id: "cron.jobs-list",
      title: "List cron jobs (schedule, enabled, routing, next run)",
      method: "GET",
      path: "/api/cron/jobs",
      tier: "safe",
      params: {
        fields: [
          {
            name: "sortBy",
            location: "query",
            type: "string",
            required: false,
            description: "Sort key; default nextRunAtMs.",
          },
          {
            name: "sortDir",
            location: "query",
            type: "string",
            required: false,
            description: "asc|desc; default asc.",
          },
        ],
        example: "GET /api/cron/jobs?sortBy=nextRunAtMs&sortDir=asc",
      },
    },
    {
      id: "cron.status",
      title: "Cron scheduler status",
      method: "GET",
      path: "/api/cron/status",
      tier: "safe",
    },
    {
      id: "cron.job-runs",
      title: "Run history for one cron job",
      method: "GET",
      path: "/api/cron/jobs/:id/runs",
      tier: "safe",
      params: {
        fields: [
          {
            name: "id",
            location: "path",
            type: "string",
            required: true,
            description: "Cron job id from cron.jobs-list.",
          },
          {
            name: "limit",
            location: "query",
            type: "number",
            required: false,
            description: "Page size; default 20.",
          },
          {
            name: "offset",
            location: "query",
            type: "number",
            required: false,
            description: "Page offset; default 0. Response includes hasMore/nextOffset.",
          },
          {
            name: "status",
            location: "query",
            type: "string",
            required: false,
            description: "Run status filter; default all.",
          },
          {
            name: "deliveryStatus",
            location: "query",
            type: "string",
            required: false,
            description: "Delivery status filter; default all.",
          },
          {
            name: "sortDir",
            location: "query",
            type: "string",
            required: false,
            description: "asc|desc; default desc (newest first).",
          },
          {
            name: "query",
            location: "query",
            type: "string",
            required: false,
            description: "Free-text filter over run entries.",
          },
        ],
        example: "GET /api/cron/jobs/morning-digest/runs?limit=20&status=error",
      },
    },
    {
      id: "cron.job-run",
      title: "Run a cron job now",
      method: "POST",
      path: "/api/cron/jobs/:id/run",
      tier: "write",
      idempotent: false,
      readOp: "cron.job-runs",
      params: {
        fields: [
          {
            name: "id",
            location: "path",
            type: "string",
            required: true,
            description:
              "Cron job id. Triggers one immediate run and waits for the result; the scheduled cadence is unchanged. Unknown ids are rejected (400).",
          },
        ],
        example: "POST /api/cron/jobs/morning-digest/run",
      },
    },
    {
      id: "cron.job-enable",
      title: "Enable a cron job",
      method: "POST",
      path: "/api/cron/jobs/:id/enable",
      tier: "write",
      idempotent: true,
      readOp: "cron.jobs-list",
      params: {
        fields: [
          {
            name: "id",
            location: "path",
            type: "string",
            required: true,
            description: "Cron job id. Enabling an already-enabled job is a no-op.",
          },
        ],
        example: "POST /api/cron/jobs/morning-digest/enable",
      },
    },
    {
      id: "cron.job-disable",
      title: "Disable a cron job",
      method: "POST",
      path: "/api/cron/jobs/:id/disable",
      tier: "write",
      idempotent: true,
      readOp: "cron.jobs-list",
      params: {
        fields: [
          {
            name: "id",
            location: "path",
            type: "string",
            required: true,
            description:
              "Cron job id. Stops future scheduled runs; history and config are kept.",
          },
        ],
        example: "POST /api/cron/jobs/morning-digest/disable",
      },
    },
    {
      id: "cron.job-prompt",
      title: "Update a cron job's prompt",
      method: "PUT",
      path: "/api/cron/jobs/:id/prompt",
      tier: "write",
      idempotent: true,
      readOp: "cron.jobs-list",
      params: {
        fields: [
          {
            name: "id",
            location: "path",
            type: "string",
            required: true,
            description: "Cron job id.",
          },
          {
            name: "message",
            location: "body",
            type: "string",
            required: true,
            description:
              "FULL replacement prompt text sent to the agent on each run — not appended. Read the current prompt from cron.jobs-list first.",
          },
        ],
        example: '{"message":"Summarize overnight alerts and post the digest."}',
      },
    },
    {
      id: "cron.job-routing",
      title: "Update a cron job's session/delivery routing",
      method: "PUT",
      path: "/api/cron/jobs/:id/routing",
      tier: "write",
      idempotent: true,
      readOp: "cron.jobs-list",
      params: {
        fields: [
          {
            name: "id",
            location: "path",
            type: "string",
            required: true,
            description: "Cron job id.",
          },
          {
            name: "sessionTarget",
            location: "body",
            type: "string",
            required: false,
            description: "Which agent session runs the job (e.g. main vs isolated).",
          },
          {
            name: "wakeMode",
            location: "body",
            type: "string",
            required: false,
            description: "How the run wakes the session (e.g. now vs next-heartbeat).",
          },
          {
            name: "deliveryMode",
            location: "body",
            type: "string",
            required: false,
            description: "How results are delivered (e.g. announce vs none).",
          },
          {
            name: "deliveryChannel",
            location: "body",
            type: "string",
            required: false,
            description: "Delivery channel (e.g. telegram).",
          },
          {
            name: "deliveryTo",
            location: "body",
            type: "string",
            required: false,
            description: "Delivery target within the channel (e.g. chat/topic id).",
          },
        ],
        example:
          '{"sessionTarget":"isolated","wakeMode":"now","deliveryMode":"announce","deliveryChannel":"telegram","deliveryTo":"-100123456"}',
      },
      notes: "Fields are validated as a set by the cron service; invalid combos are rejected (400).",
    },
    {
      id: "cron.job-usage",
      title: "Token/cost usage for one cron job",
      method: "GET",
      path: "/api/cron/jobs/:id/usage",
      tier: "safe",
      params: {
        fields: [
          {
            name: "id",
            location: "path",
            type: "string",
            required: true,
            description: "Cron job id.",
          },
          {
            name: "days",
            location: "query",
            type: "number",
            required: false,
            description: "Lookback window in days; omitted/0 = all time.",
          },
        ],
        example: "GET /api/cron/jobs/morning-digest/usage?days=7",
      },
    },
    {
      id: "cron.job-trends",
      title: "Run trend series for one cron job",
      method: "GET",
      path: "/api/cron/jobs/:id/trends",
      tier: "safe",
      params: {
        fields: [
          {
            name: "id",
            location: "path",
            type: "string",
            required: true,
            description: "Cron job id.",
          },
          {
            name: "range",
            location: "query",
            type: "string",
            required: false,
            description: "Trend range, e.g. 7d (default).",
          },
        ],
        example: "GET /api/cron/jobs/morning-digest/trends?range=7d",
      },
    },
    {
      id: "cron.usage-bulk",
      title: "Usage rollup across all cron jobs",
      method: "GET",
      path: "/api/cron/usage/bulk",
      tier: "safe",
      params: {
        fields: [
          {
            name: "days",
            location: "query",
            type: "number",
            required: false,
            description: "Lookback window in days; omitted/0 = all time.",
          },
        ],
        example: "GET /api/cron/usage/bulk?days=30",
      },
    },
    {
      id: "cron.runs-bulk",
      title: "Recent runs across all cron jobs",
      method: "GET",
      path: "/api/cron/runs/bulk",
      tier: "safe",
      params: {
        fields: [
          {
            name: "sinceMs",
            location: "query",
            type: "number",
            required: false,
            description: "Only runs at/after this epoch-ms; default 0 (all).",
          },
          {
            name: "limitPerJob",
            location: "query",
            type: "number",
            required: false,
            description: "Max runs returned per job; default 20.",
          },
          {
            name: "status",
            location: "query",
            type: "string",
            required: false,
            description: "Run status filter; default all.",
          },
          {
            name: "deliveryStatus",
            location: "query",
            type: "string",
            required: false,
            description: "Delivery status filter; default all.",
          },
          {
            name: "sortDir",
            location: "query",
            type: "string",
            required: false,
            description: "asc|desc; default desc.",
          },
        ],
        example: "GET /api/cron/runs/bulk?limitPerJob=10&status=error",
      },
    },
  ],
};
