module.exports = {
  domain: "watchdog",
  title: "Watchdog",
  ops: [
    {
      id: "watchdog.status",
      title: "Watchdog + gateway health status",
      method: "GET",
      path: "/api/watchdog/status",
      tier: "safe",
    },
    {
      id: "watchdog.events",
      title: "Watchdog event log (includes agent_admin audit rows)",
      method: "GET",
      path: "/api/watchdog/events",
      tier: "safe",
      params: {
        fields: [
          {
            name: "limit",
            location: "query",
            type: "number",
            required: false,
            description: "Max events to return.",
          },
        ],
        example: "GET /api/watchdog/events?limit=50",
      },
    },
    {
      id: "watchdog.logs",
      title: "Recent gateway/process log lines",
      method: "GET",
      path: "/api/watchdog/logs",
      tier: "safe",
    },
    {
      id: "watchdog.resources",
      title:
        "Container resource usage (memory, CPU, disk, processes, event loop) + capacity profile",
      method: "GET",
      path: "/api/watchdog/resources",
      tier: "safe",
    },
    {
      id: "watchdog.settings.read",
      title: "Read watchdog settings",
      method: "GET",
      path: "/api/watchdog/settings",
      tier: "safe",
    },
    {
      id: "watchdog.settings.update",
      title: "Update watchdog settings (autoRepair, notificationsEnabled)",
      method: "PUT",
      path: "/api/watchdog/settings",
      tier: "write",
      idempotent: true,
      readOp: "watchdog.settings.read",
      params: {
        fields: [
          {
            name: "autoRepair",
            location: "body",
            type: "boolean",
            required: false,
            description: "Run `openclaw doctor --fix` automatically on crash loops.",
          },
          {
            name: "notificationsEnabled",
            location: "body",
            type: "boolean",
            required: false,
            description: "Watchdog alerts to paired channels.",
          },
        ],
        example: '{"notificationsEnabled": false}',
      },
      notes: "Persisted as env flags; takes effect immediately, no restart.",
    },
    {
      id: "watchdog.repair",
      title: "Trigger auto-repair (doctor --fix + gateway relaunch)",
      method: "POST",
      path: "/api/watchdog/repair",
      tier: "dangerous",
      hint: "Repair relaunches the gateway — the agent's own session may drop.",
    },
    {
      id: "watchdog.resume-channels",
      title: "Resume channels suppressed by safe mode",
      method: "POST",
      path: "/api/watchdog/resume-channels",
      tier: "write",
    },
    {
      id: "watchdog.test-notification",
      title: "Send a test watchdog notification",
      method: "POST",
      path: "/api/watchdog/test-notification",
      tier: "write",
      idempotent: false,
    },
    // The interactive terminal is a human debugging surface: it executes
    // terminal input against the box. Never available to the agent actor.
    {
      id: "watchdog.terminal.session",
      title: "Open watchdog terminal session (human-only)",
      method: "POST",
      path: "/api/watchdog/terminal/session",
      tier: "denied",
      hint: "The watchdog terminal is operator-only; use the Setup UI.",
    },
    {
      id: "watchdog.terminal.input",
      title: "Watchdog terminal input (human-only)",
      method: "POST",
      path: "/api/watchdog/terminal/input",
      tier: "denied",
      hint: "The watchdog terminal is operator-only; use the Setup UI.",
    },
    {
      id: "watchdog.terminal.output",
      title: "Watchdog terminal output (human-only)",
      method: "GET",
      path: "/api/watchdog/terminal/output",
      tier: "denied",
      hint: "The watchdog terminal is operator-only; use the Setup UI.",
    },
    {
      id: "watchdog.terminal.close",
      title: "Close watchdog terminal session (human-only)",
      method: "POST",
      path: "/api/watchdog/terminal/close",
      tier: "denied",
      hint: "The watchdog terminal is operator-only; use the Setup UI.",
    },
  ],
};
